apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            # Instead of using value directly we could also use secrets
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-storage
              mountPath: "/var/lib/mysql"
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-persistent-claim
---
apiVersion: v1
kind: Service
metadata:
  name: booksdb
  namespace: logs
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
  #kubectl run -it --rm --image=mysql:8.0 --restart=Never mysql-client -- mysql -h mysql -ppassword
  #sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
  #sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld